# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
